spring:
  # 默认启动
  profiles:
    active: dev
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    validationQuery: SELECT 1
    initialSize: 5
    # 配置获取连接等待超时的时间
    maxWait: 60000
    poolPreparedStatements: true
    filters: stat,wall
    # 阿里爸爸数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://${baseHostName}:${mySQLPort}/${baseMysqlDatabase}?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    maxPoolPreparedStatementPerConnectionSize: 20
    username: ${mySQLUsername}
    password: ${mySQLPassword}
    testOnBorrow: false
    testWhileIdle: true
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    testOnReturn: false
    # mysql 驱动
    driver-class-name: com.mysql.jdbc.Driver
    # 初始化大小，最小，最大
    maxActive: 20
    minIdle: 5
    tomcat:
      initSQL: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
  resources:
    # 静态资源文件
    static-locations: classpath:/templates/dist/,classpath:/static/
  jpa:
    database: mysql
    # 显示sql
    show-sql: ${showSQL}
    hibernate:
      ddl-auto: none
    # 方言
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
  mvc:
    # 视图
    view:
      prefix: classpath:/templates/
      suffix: .html
  redis:
    # Redis服务器连接密码（默认为空）
    password: ${redisPassword}
    # Redis数据库索引（默认为0）
    database: ${baseRedisDatabase}
    # Redis服务器连接端口
    port: ${redisPort}
    pool:
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
    # Redis服务器地址
    host: ${baseHostName}
    # 连接超时时间（毫秒）
    timeout: 0

# jar 包运行时候的端口号
server:
  port: ${basePort}

mybatis:
  type-aliases-package: com.bnuz.bbkt.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

projectUrl:
  wechatMpAuthorize: http://fxm.nat300.top

  jackson:
    default-property-inclusion: non_null
  aop:
    auto: true #启动aop配置